# Generated by Django 5.2.1 on 2025-09-22 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito_PK', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_usuario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioFK')),
            ],
            options={
                'verbose_name': 'Carrito',
                'db_table': 'carrito',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallesCarrito',
            fields=[
                ('id_detalles_carrito_PK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('id_carrito_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carrito', verbose_name='DetallesCarrito')),
                ('id_producto_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos', verbose_name='ProductoFK')),
            ],
            options={
                'verbose_name': 'Producto en Carrito',
                'db_table': 'carrito_productos',
                'ordering': ['id_carrito_FK'],
            },
        ),
    ]
