# Generated by Django 3.2.8 on 2025-10-26 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_productos_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito_PK', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_usuario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioFK')),
            ],
            options={
                'verbose_name': 'Carrito',
                'db_table': 'carrito',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido_PK', models.AutoField(primary_key=True, serialize=False)),
                ('quien', models.CharField(max_length=200, verbose_name='Para quien')),
                ('tipo_entrega', models.CharField(max_length=50, verbose_name='Tipo de entrega')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Metodo de pago')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'db_table': 'pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_item_PK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'db_table': 'pedido_items',
            },
        ),
        migrations.CreateModel(
            name='DetallesCarrito',
            fields=[
                ('id_detalles_carrito_PK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('id_carrito_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carrito', verbose_name='DetallesCarrito')),
                ('id_producto_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos', verbose_name='ProductoFK')),
            ],
            options={
                'verbose_name': 'Producto en Carrito',
                'db_table': 'carrito_productos',
                'ordering': ['id_carrito_FK'],
            },
        ),
    ]
