# Generated by Django 3.2.8 on 2025-10-23 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_detallescarrito_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido_PK', models.AutoField(primary_key=True, serialize=False)),
                ('quien', models.CharField(max_length=200, verbose_name='Para quien')),
                ('tipo_entrega', models.CharField(max_length=50, verbose_name='Tipo de entrega')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Metodo de pago')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'db_table': 'pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_item_PK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'db_table': 'pedido_items',
            },
        ),
    ]
