# Generated by Django 5.2.4 on 2025-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria_PK', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id_categoria_PK'],
            },
        ),
    ]
