# Generated by Django 5.2.4 on 2025-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clienteprofile_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='anio_nacimiento',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de nacimiento'),
        ),
    ]
