# Generated by Django 5.2.4 on 2025-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clienteprofile_anio_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteprofile',
            name='anio_nacimiento',
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
