# Generated by Django 5.2.4 on 2025-07-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('vendedor', 'Vendedor'), ('distribuidor', 'Distribuidor')], default='empleado', max_length=20),
        ),
    ]
