# Generated by Django 5.2.4 on 2025-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_alter_customuser_is_cliente_alter_customuser_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioRegistrado',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('vendedor', 'Vendedor'), ('distribuidor', 'Distribuidor'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
