# Generated by Django 5.2.4 on 2025-10-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_customuser_apellido_customuser_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
    ]
