# Generated by Django 5.2.1 on 2025-07-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='estatus',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
