# Generated by Django 5.2.1 on 2025-06-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Proveedores',
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedores'},
        ),
    ]
