# Generated by Django 5.2.1 on 2025-06-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_rename_proveedor_proveedores_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'ordering': ['nombre']},
        ),
    ]
