# Generated by Django 5.2.1 on 2025-06-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor'},
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='proveedores',
        ),
    ]
