<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-07-04 14:11
=======
# Generated by Django 5.2.4 on 2025-07-07 00:12
>>>>>>> Cambio-muchachos

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_proveedores_options_alter_proveedores_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'ordering': ['id_proveedor_PK'], 'verbose_name': 'Proveedor'},
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
